### PR TITLE
fix deprecation warning in Rails 3

### PR DESCRIPTION
**Pull request by alexreisner**
This gem is fantastic. This commit gets rid of a deprecation warning about the RAILS_ENV constant. Thanks!

### CODE REVIEW

**Comment by mislav** [comment]
Wow, you're fast at contributing! I didn't even know anyone noticed this lib.

I know that RAILS_ENV is deprecated in Rails 3, but in Rails 2 at this point `Rails.env` isn't accessible because it's too early and required activesupport bit isn't loaded yet. If you have a solution for both Rails 2 & 3, I'd be glad to merge it in.

**Comment by alexreisner** [comment]
It seems like you published choices just as I had a need for it!

I'm having trouble getting it to work in Rails 2 at all. If I add this to my initializer block:

```
config.gem 'choices'
config.from_file 'settings.yml'
```

I get:

```
undefined method `from_file' for #<Rails::Configuration:0xb721afe0>
```

If I add `require 'choices'` between the above two lines I get:

```
...gems/choices-0.2.0/lib/choices/rails.rb:21:in `from_file':NoMethodError: undefined method `update' for nil:NilClass
```

Manually requiring Hashie doesn't seem to make a difference. Do I have to use bundler?

**Comment by marcinbunsch** [comment]
Mislav - thanks for sharing choices, it's really useful. I just added it to a Rails 3 app and just noticed that the deprecation warning is still there. I made a small fix that should allow both:

https://github.com/marcinbunsch/choices/commit/dd279ffc202f2f6b27ee99bbaad62a5d39ad779d

I saw that this pull request and discussion was still open so did not want to pollute the issues with a duplicate pull request.

**Comment by marcinbunsch** [comment]
Rails 3: use Rails.env instead of RAILS_ENV

closed by 632ee1eb3527ba658e04ce78b0db7f10efde31d8

**Pull request closed without merging**
